### ISSUE TITLE
Multiplying TICKS by TICKS

### ISSUE THREAD

**Issue by Rodney-Lewis** [FRC-1250/Team-1250-PowerUp-Code#3]
https://github.com/FRC-1250/Team-1250-PowerUp-Code/blob/3ee963df903e449465cc7e96a948753a82556c92/src/org/usfirst/frc/team1250/robot/subsystems/Sub_Elevator.java#L66

Used in our command isfinished logic for all heights. For example:

`(Robot.s_elevator.getLiftPosTicks() == Robot.s_elevator.ELE_TICKS * Robot.s_elevator.SWITCH_POS)`

It'll never end on this criteria. But as its been mentioned, even using == it'll be difficult to be so exact for this end case so I believe we could rethink this. 

Possibly use a small range like +-100 ticks (About 1/10 of an inch), this may be a more realistic end case but still fairly precise one.

**Comment by ruiqim** [comment]
I mentioned that to Damien Yesterday as well. We were discussing how to go about fixing this. Possibly What you said and implementing a timeout so that even if it never comes within the range in the allotted time, the setpoint should be set to the global variable `eleSetpoint` such that when we return to `Cmd_EleManual`, the manual mode will remember to keep the lift at the setpoint.

**Comment by RincewindBoi** [comment]
Resolved tick multiplication in commit: eb4e0fadef5167489f1bb1b8c9439bfeeb2e3259. Keeping open until we think of a better way to handle this case.

**Comment by Rodney-Lewis** [comment]
Resolved by using one side of the drive train to land in a **_range_** the encoder finds acceptable and stops.
